// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createMeasurement, currentUser, deleteLabUpload, listBiomarkerCatalog, listBiomarkers, listLabUploads, liveness, type Options, readiness, uploadLab } from '../sdk.gen';
import type { CreateMeasurementData, CreateMeasurementError, CreateMeasurementResponse, CurrentUserData, CurrentUserResponse, DeleteLabUploadData, DeleteLabUploadError, DeleteLabUploadResponse, ListBiomarkerCatalogData, ListBiomarkerCatalogResponse, ListBiomarkersData, ListBiomarkersResponse, ListLabUploadsData, ListLabUploadsResponse, LivenessData, LivenessResponse, ReadinessData, ReadinessResponse, UploadLabData, UploadLabError, UploadLabResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const livenessQueryKey = (options?: Options<LivenessData>) => createQueryKey('liveness', options);

/**
 * Liveness
 *
 * Liveness probe — no dependencies. Used by the Cloud Run startup probe.
 */
export const livenessOptions = (options?: Options<LivenessData>) => queryOptions<LivenessResponse, DefaultError, LivenessResponse, ReturnType<typeof livenessQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await liveness({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: livenessQueryKey(options)
});

export const readinessQueryKey = (options?: Options<ReadinessData>) => createQueryKey('readiness', options);

/**
 * Readiness
 *
 * Readiness probe — confirms the Cloud SQL (IAM-auth) connection works.
 */
export const readinessOptions = (options?: Options<ReadinessData>) => queryOptions<ReadinessResponse, DefaultError, ReadinessResponse, ReturnType<typeof readinessQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readiness({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readinessQueryKey(options)
});

export const currentUserQueryKey = (options?: Options<CurrentUserData>) => createQueryKey('currentUser', options);

/**
 * Read Current User
 *
 * Return the authenticated caller's identity.
 *
 * Proves the full loop: the Bearer token is verified against Clerk's JWKS
 * and the caller is resolved to (or JIT-created as) a local users row.
 */
export const currentUserOptions = (options?: Options<CurrentUserData>) => queryOptions<CurrentUserResponse, DefaultError, CurrentUserResponse, ReturnType<typeof currentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await currentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: currentUserQueryKey(options)
});

export const listLabUploadsQueryKey = (options?: Options<ListLabUploadsData>) => createQueryKey('listLabUploads', options);

/**
 * List Lab Uploads
 *
 * Return the caller's uploaded lab reports, newest first.
 */
export const listLabUploadsOptions = (options?: Options<ListLabUploadsData>) => queryOptions<ListLabUploadsResponse, DefaultError, ListLabUploadsResponse, ReturnType<typeof listLabUploadsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listLabUploads({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listLabUploadsQueryKey(options)
});

/**
 * Upload Lab
 *
 * Upload a lab PDF, parse it into biomarker measurements, and store both.
 *
 * Synchronous end-to-end (~10-30 s). The original PDF is kept in GCS and the
 * upload row is retained even on parse failure, for debugging and retry.
 */
export const uploadLabMutation = (options?: Partial<Options<UploadLabData>>): UseMutationOptions<UploadLabResponse, UploadLabError, Options<UploadLabData>> => {
    const mutationOptions: UseMutationOptions<UploadLabResponse, UploadLabError, Options<UploadLabData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadLab({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Lab Upload
 *
 * Delete an uploaded report; optionally its measurements, else orphan them.
 */
export const deleteLabUploadMutation = (options?: Partial<Options<DeleteLabUploadData>>): UseMutationOptions<DeleteLabUploadResponse, DeleteLabUploadError, Options<DeleteLabUploadData>> => {
    const mutationOptions: UseMutationOptions<DeleteLabUploadResponse, DeleteLabUploadError, Options<DeleteLabUploadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteLabUpload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBiomarkerCatalogQueryKey = (options?: Options<ListBiomarkerCatalogData>) => createQueryKey('listBiomarkerCatalog', options);

/**
 * List Biomarker Catalog
 *
 * Return the full seeded biomarker catalogue, for manual-entry pickers.
 */
export const listBiomarkerCatalogOptions = (options?: Options<ListBiomarkerCatalogData>) => queryOptions<ListBiomarkerCatalogResponse, DefaultError, ListBiomarkerCatalogResponse, ReturnType<typeof listBiomarkerCatalogQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBiomarkerCatalog({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBiomarkerCatalogQueryKey(options)
});

/**
 * Create Measurement
 *
 * Record a manually entered measurement against a catalogue biomarker.
 */
export const createMeasurementMutation = (options?: Partial<Options<CreateMeasurementData>>): UseMutationOptions<CreateMeasurementResponse, CreateMeasurementError, Options<CreateMeasurementData>> => {
    const mutationOptions: UseMutationOptions<CreateMeasurementResponse, CreateMeasurementError, Options<CreateMeasurementData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createMeasurement({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBiomarkersQueryKey = (options?: Options<ListBiomarkersData>) => createQueryKey('listBiomarkers', options);

/**
 * List Biomarkers
 *
 * Return each biomarker the caller has measurements for, with its time series.
 *
 * Values, units, and reference ranges are verbatim from the lab report;
 * canonical_unit is catalogue context. Series are sorted by measurement date
 * ascending, so the latest value is the last element.
 */
export const listBiomarkersOptions = (options?: Options<ListBiomarkersData>) => queryOptions<ListBiomarkersResponse, DefaultError, ListBiomarkersResponse, ReturnType<typeof listBiomarkersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBiomarkers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBiomarkersQueryKey(options)
});
