// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { confirmLabUpload, createBiomarkerMeasurements, currentUser, deleteBiomarkerMeasurements, deleteLabUpload, getBiomarkerSeries, getLabUpload, listBiomarkers, listBiomarkerSeries, listLabUploads, liveness, type Options, readiness, updateBiomarkerMeasurements, updateLabDraft, uploadLab } from '../sdk.gen';
import type { ConfirmLabUploadData, ConfirmLabUploadError, ConfirmLabUploadResponse, CreateBiomarkerMeasurementsData, CreateBiomarkerMeasurementsError, CreateBiomarkerMeasurementsResponse, CurrentUserData, CurrentUserResponse, DeleteBiomarkerMeasurementsData, DeleteBiomarkerMeasurementsError, DeleteBiomarkerMeasurementsResponse, DeleteLabUploadData, DeleteLabUploadError, DeleteLabUploadResponse, GetBiomarkerSeriesData, GetBiomarkerSeriesError, GetBiomarkerSeriesResponse, GetLabUploadData, GetLabUploadError, GetLabUploadResponse, ListBiomarkersData, ListBiomarkerSeriesData, ListBiomarkerSeriesResponse, ListBiomarkersResponse, ListLabUploadsData, ListLabUploadsResponse, LivenessData, LivenessResponse, ReadinessData, ReadinessResponse, UpdateBiomarkerMeasurementsData, UpdateBiomarkerMeasurementsError, UpdateBiomarkerMeasurementsResponse, UpdateLabDraftData, UpdateLabDraftError, UpdateLabDraftResponse, UploadLabData, UploadLabError, UploadLabResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const livenessQueryKey = (options?: Options<LivenessData>) => createQueryKey('liveness', options);

/**
 * Liveness
 *
 * Liveness probe — no dependencies. Used by the Cloud Run startup probe.
 */
export const livenessOptions = (options?: Options<LivenessData>) => queryOptions<LivenessResponse, DefaultError, LivenessResponse, ReturnType<typeof livenessQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await liveness({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: livenessQueryKey(options)
});

export const readinessQueryKey = (options?: Options<ReadinessData>) => createQueryKey('readiness', options);

/**
 * Readiness
 *
 * Readiness probe — confirms the Cloud SQL (IAM-auth) connection works.
 */
export const readinessOptions = (options?: Options<ReadinessData>) => queryOptions<ReadinessResponse, DefaultError, ReadinessResponse, ReturnType<typeof readinessQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readiness({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readinessQueryKey(options)
});

export const currentUserQueryKey = (options?: Options<CurrentUserData>) => createQueryKey('currentUser', options);

/**
 * Read Current User
 *
 * Return the authenticated caller's identity.
 *
 * Proves the full loop: the Bearer token is verified against Clerk's JWKS
 * and the caller is resolved to (or JIT-created as) a local users row.
 */
export const currentUserOptions = (options?: Options<CurrentUserData>) => queryOptions<CurrentUserResponse, DefaultError, CurrentUserResponse, ReturnType<typeof currentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await currentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: currentUserQueryKey(options)
});

export const listLabUploadsQueryKey = (options?: Options<ListLabUploadsData>) => createQueryKey('listLabUploads', options);

/**
 * List Lab Uploads
 *
 * Return the caller's uploaded lab reports, newest first.
 */
export const listLabUploadsOptions = (options?: Options<ListLabUploadsData>) => queryOptions<ListLabUploadsResponse, DefaultError, ListLabUploadsResponse, ReturnType<typeof listLabUploadsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listLabUploads({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listLabUploadsQueryKey(options)
});

/**
 * Upload Lab
 *
 * Accept a lab PDF for parsing into a reviewable draft.
 *
 * Validates the request here; the service stores the PDF and parses it. The
 * caller polls GET /lab-uploads/{id} until the draft is ready to review.
 */
export const uploadLabMutation = (options?: Partial<Options<UploadLabData>>): UseMutationOptions<UploadLabResponse, UploadLabError, Options<UploadLabData>> => {
    const mutationOptions: UseMutationOptions<UploadLabResponse, UploadLabError, Options<UploadLabData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadLab({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Lab Upload
 *
 * Delete an uploaded report; optionally its measurements, else orphan them.
 */
export const deleteLabUploadMutation = (options?: Partial<Options<DeleteLabUploadData>>): UseMutationOptions<DeleteLabUploadResponse, DeleteLabUploadError, Options<DeleteLabUploadData>> => {
    const mutationOptions: UseMutationOptions<DeleteLabUploadResponse, DeleteLabUploadError, Options<DeleteLabUploadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteLabUpload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getLabUploadQueryKey = (options: Options<GetLabUploadData>) => createQueryKey('getLabUpload', options);

/**
 * Get Lab Upload
 *
 * Return one upload's status, and its reviewable draft while awaiting review.
 */
export const getLabUploadOptions = (options: Options<GetLabUploadData>) => queryOptions<GetLabUploadResponse, GetLabUploadError, GetLabUploadResponse, ReturnType<typeof getLabUploadQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLabUpload({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLabUploadQueryKey(options)
});

/**
 * Update Lab Draft
 *
 * Apply the user's review edits to a draft; only while awaiting review.
 */
export const updateLabDraftMutation = (options?: Partial<Options<UpdateLabDraftData>>): UseMutationOptions<UpdateLabDraftResponse, UpdateLabDraftError, Options<UpdateLabDraftData>> => {
    const mutationOptions: UseMutationOptions<UpdateLabDraftResponse, UpdateLabDraftError, Options<UpdateLabDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateLabDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Confirm Lab Upload
 *
 * Commit the kept, mapped draft measurements into the biomarker record.
 */
export const confirmLabUploadMutation = (options?: Partial<Options<ConfirmLabUploadData>>): UseMutationOptions<ConfirmLabUploadResponse, ConfirmLabUploadError, Options<ConfirmLabUploadData>> => {
    const mutationOptions: UseMutationOptions<ConfirmLabUploadResponse, ConfirmLabUploadError, Options<ConfirmLabUploadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await confirmLabUpload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBiomarkersQueryKey = (options?: Options<ListBiomarkersData>) => createQueryKey('listBiomarkers', options);

/**
 * List Biomarkers
 *
 * Return the full seeded biomarker catalogue, for manual-entry pickers.
 */
export const listBiomarkersOptions = (options?: Options<ListBiomarkersData>) => queryOptions<ListBiomarkersResponse, DefaultError, ListBiomarkersResponse, ReturnType<typeof listBiomarkersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBiomarkers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBiomarkersQueryKey(options)
});

export const listBiomarkerSeriesQueryKey = (options?: Options<ListBiomarkerSeriesData>) => createQueryKey('listBiomarkerSeries', options);

/**
 * List Biomarker Series
 *
 * Return each biomarker the caller has measurements for, with its time series.
 *
 * Values, units, and reference ranges are verbatim from the lab report;
 * canonical_unit is catalogue context. Series are sorted by measurement date
 * ascending, so the latest value is the last element.
 */
export const listBiomarkerSeriesOptions = (options?: Options<ListBiomarkerSeriesData>) => queryOptions<ListBiomarkerSeriesResponse, DefaultError, ListBiomarkerSeriesResponse, ReturnType<typeof listBiomarkerSeriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBiomarkerSeries({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBiomarkerSeriesQueryKey(options)
});

export const getBiomarkerSeriesQueryKey = (options: Options<GetBiomarkerSeriesData>) => createQueryKey('getBiomarkerSeries', options);

/**
 * Get Biomarker Series
 *
 * Return one biomarker's time series; empty for a known slug with no data.
 */
export const getBiomarkerSeriesOptions = (options: Options<GetBiomarkerSeriesData>) => queryOptions<GetBiomarkerSeriesResponse, GetBiomarkerSeriesError, GetBiomarkerSeriesResponse, ReturnType<typeof getBiomarkerSeriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBiomarkerSeries({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBiomarkerSeriesQueryKey(options)
});

/**
 * Delete Biomarker Measurements
 *
 * Delete the caller's measurements; all-or-nothing.
 */
export const deleteBiomarkerMeasurementsMutation = (options?: Partial<Options<DeleteBiomarkerMeasurementsData>>): UseMutationOptions<DeleteBiomarkerMeasurementsResponse, DeleteBiomarkerMeasurementsError, Options<DeleteBiomarkerMeasurementsData>> => {
    const mutationOptions: UseMutationOptions<DeleteBiomarkerMeasurementsResponse, DeleteBiomarkerMeasurementsError, Options<DeleteBiomarkerMeasurementsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteBiomarkerMeasurements({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Biomarker Measurements
 *
 * Update the caller's measurements; omitted fields are left untouched.
 */
export const updateBiomarkerMeasurementsMutation = (options?: Partial<Options<UpdateBiomarkerMeasurementsData>>): UseMutationOptions<UpdateBiomarkerMeasurementsResponse, UpdateBiomarkerMeasurementsError, Options<UpdateBiomarkerMeasurementsData>> => {
    const mutationOptions: UseMutationOptions<UpdateBiomarkerMeasurementsResponse, UpdateBiomarkerMeasurementsError, Options<UpdateBiomarkerMeasurementsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBiomarkerMeasurements({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Biomarker Measurements
 *
 * Record measurements against catalogue biomarkers; all-or-nothing.
 */
export const createBiomarkerMeasurementsMutation = (options?: Partial<Options<CreateBiomarkerMeasurementsData>>): UseMutationOptions<CreateBiomarkerMeasurementsResponse, CreateBiomarkerMeasurementsError, Options<CreateBiomarkerMeasurementsData>> => {
    const mutationOptions: UseMutationOptions<CreateBiomarkerMeasurementsResponse, CreateBiomarkerMeasurementsError, Options<CreateBiomarkerMeasurementsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBiomarkerMeasurements({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
