// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { ConfirmLabUploadData, ConfirmLabUploadErrors, ConfirmLabUploadResponses, CreateBiomarkerMeasurementsData, CreateBiomarkerMeasurementsErrors, CreateBiomarkerMeasurementsResponses, CurrentUserData, CurrentUserResponses, DeleteBiomarkerMeasurementsData, DeleteBiomarkerMeasurementsErrors, DeleteBiomarkerMeasurementsResponses, DeleteLabUploadData, DeleteLabUploadErrors, DeleteLabUploadResponses, GetBiomarkerSeriesData, GetBiomarkerSeriesErrors, GetBiomarkerSeriesResponses, GetLabUploadData, GetLabUploadErrors, GetLabUploadResponses, ListBiomarkersData, ListBiomarkerSeriesData, ListBiomarkerSeriesResponses, ListBiomarkersResponses, ListLabUploadsData, ListLabUploadsResponses, LivenessData, LivenessResponses, ReadinessData, ReadinessResponses, UpdateBiomarkerMeasurementsData, UpdateBiomarkerMeasurementsErrors, UpdateBiomarkerMeasurementsResponses, UpdateLabDraftData, UpdateLabDraftErrors, UpdateLabDraftResponses, UploadLabData, UploadLabErrors, UploadLabResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness
 *
 * Liveness probe — no dependencies. Used by the Cloud Run startup probe.
 */
export const liveness = <ThrowOnError extends boolean = false>(options?: Options<LivenessData, ThrowOnError>): RequestResult<LivenessResponses, unknown, ThrowOnError> => (options?.client ?? client).get<LivenessResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Readiness
 *
 * Readiness probe — confirms the Cloud SQL (IAM-auth) connection works.
 */
export const readiness = <ThrowOnError extends boolean = false>(options?: Options<ReadinessData, ThrowOnError>): RequestResult<ReadinessResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadinessResponses, unknown, ThrowOnError>({ url: '/readyz', ...options });

/**
 * Read Current User
 *
 * Return the authenticated caller's identity.
 *
 * Proves the full loop: the Bearer token is verified against Clerk's JWKS
 * and the caller is resolved to (or JIT-created as) a local users row.
 */
export const currentUser = <ThrowOnError extends boolean = false>(options?: Options<CurrentUserData, ThrowOnError>): RequestResult<CurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CurrentUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me',
    ...options
});

/**
 * List Lab Uploads
 *
 * Return the caller's uploaded lab reports, newest first.
 */
export const listLabUploads = <ThrowOnError extends boolean = false>(options?: Options<ListLabUploadsData, ThrowOnError>): RequestResult<ListLabUploadsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListLabUploadsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/lab-uploads',
    ...options
});

/**
 * Upload Lab
 *
 * Accept a lab PDF for parsing into a reviewable draft.
 *
 * Validates the request here; the service stores the PDF and parses it. The
 * caller polls GET /lab-uploads/{id} until the draft is ready to review.
 */
export const uploadLab = <ThrowOnError extends boolean = false>(options: Options<UploadLabData, ThrowOnError>): RequestResult<UploadLabResponses, UploadLabErrors, ThrowOnError> => (options.client ?? client).post<UploadLabResponses, UploadLabErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/lab-uploads',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete Lab Upload
 *
 * Delete an uploaded report; optionally its measurements, else orphan them.
 */
export const deleteLabUpload = <ThrowOnError extends boolean = false>(options: Options<DeleteLabUploadData, ThrowOnError>): RequestResult<DeleteLabUploadResponses, DeleteLabUploadErrors, ThrowOnError> => (options.client ?? client).delete<DeleteLabUploadResponses, DeleteLabUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/lab-uploads/{upload_id}',
    ...options
});

/**
 * Get Lab Upload
 *
 * Return one upload's status, and its reviewable draft while awaiting review.
 */
export const getLabUpload = <ThrowOnError extends boolean = false>(options: Options<GetLabUploadData, ThrowOnError>): RequestResult<GetLabUploadResponses, GetLabUploadErrors, ThrowOnError> => (options.client ?? client).get<GetLabUploadResponses, GetLabUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/lab-uploads/{upload_id}',
    ...options
});

/**
 * Update Lab Draft
 *
 * Apply the user's review edits to a draft; only while awaiting review.
 */
export const updateLabDraft = <ThrowOnError extends boolean = false>(options: Options<UpdateLabDraftData, ThrowOnError>): RequestResult<UpdateLabDraftResponses, UpdateLabDraftErrors, ThrowOnError> => (options.client ?? client).patch<UpdateLabDraftResponses, UpdateLabDraftErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/lab-uploads/{upload_id}/draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Confirm Lab Upload
 *
 * Commit the kept, mapped draft measurements into the biomarker record.
 */
export const confirmLabUpload = <ThrowOnError extends boolean = false>(options: Options<ConfirmLabUploadData, ThrowOnError>): RequestResult<ConfirmLabUploadResponses, ConfirmLabUploadErrors, ThrowOnError> => (options.client ?? client).post<ConfirmLabUploadResponses, ConfirmLabUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/lab-uploads/{upload_id}/confirm',
    ...options
});

/**
 * List Biomarkers
 *
 * Return the full seeded biomarker catalogue, for manual-entry pickers.
 */
export const listBiomarkers = <ThrowOnError extends boolean = false>(options?: Options<ListBiomarkersData, ThrowOnError>): RequestResult<ListBiomarkersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListBiomarkersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/biomarkers',
    ...options
});

/**
 * List Biomarker Series
 *
 * Return each biomarker the caller has measurements for, with its time series.
 *
 * Values, units, and reference ranges are verbatim from the lab report;
 * canonical_unit is catalogue context. Series are sorted by measurement date
 * ascending, so the latest value is the last element.
 */
export const listBiomarkerSeries = <ThrowOnError extends boolean = false>(options?: Options<ListBiomarkerSeriesData, ThrowOnError>): RequestResult<ListBiomarkerSeriesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListBiomarkerSeriesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/biomarker-series',
    ...options
});

/**
 * Get Biomarker Series
 *
 * Return one biomarker's time series; empty for a known slug with no data.
 */
export const getBiomarkerSeries = <ThrowOnError extends boolean = false>(options: Options<GetBiomarkerSeriesData, ThrowOnError>): RequestResult<GetBiomarkerSeriesResponses, GetBiomarkerSeriesErrors, ThrowOnError> => (options.client ?? client).get<GetBiomarkerSeriesResponses, GetBiomarkerSeriesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/biomarker-series/{slug}',
    ...options
});

/**
 * Delete Biomarker Measurements
 *
 * Delete the caller's measurements; all-or-nothing.
 */
export const deleteBiomarkerMeasurements = <ThrowOnError extends boolean = false>(options: Options<DeleteBiomarkerMeasurementsData, ThrowOnError>): RequestResult<DeleteBiomarkerMeasurementsResponses, DeleteBiomarkerMeasurementsErrors, ThrowOnError> => (options.client ?? client).delete<DeleteBiomarkerMeasurementsResponses, DeleteBiomarkerMeasurementsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/biomarker-measurements',
    ...options
});

/**
 * Update Biomarker Measurements
 *
 * Update the caller's measurements; omitted fields are left untouched.
 */
export const updateBiomarkerMeasurements = <ThrowOnError extends boolean = false>(options: Options<UpdateBiomarkerMeasurementsData, ThrowOnError>): RequestResult<UpdateBiomarkerMeasurementsResponses, UpdateBiomarkerMeasurementsErrors, ThrowOnError> => (options.client ?? client).patch<UpdateBiomarkerMeasurementsResponses, UpdateBiomarkerMeasurementsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/biomarker-measurements',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Biomarker Measurements
 *
 * Record measurements against catalogue biomarkers; all-or-nothing.
 */
export const createBiomarkerMeasurements = <ThrowOnError extends boolean = false>(options: Options<CreateBiomarkerMeasurementsData, ThrowOnError>): RequestResult<CreateBiomarkerMeasurementsResponses, CreateBiomarkerMeasurementsErrors, ThrowOnError> => (options.client ?? client).post<CreateBiomarkerMeasurementsResponses, CreateBiomarkerMeasurementsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/biomarker-measurements',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
