// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CurrentUserData, CurrentUserResponses, ListBiomarkersData, ListBiomarkersResponses, LivenessData, LivenessResponses, ReadinessData, ReadinessResponses, UploadLabData, UploadLabErrors, UploadLabResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness
 *
 * Liveness probe — no dependencies. Used by the Cloud Run startup probe.
 */
export const liveness = <ThrowOnError extends boolean = false>(options?: Options<LivenessData, ThrowOnError>): RequestResult<LivenessResponses, unknown, ThrowOnError> => (options?.client ?? client).get<LivenessResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Readiness
 *
 * Readiness probe — confirms the Cloud SQL (IAM-auth) connection works.
 */
export const readiness = <ThrowOnError extends boolean = false>(options?: Options<ReadinessData, ThrowOnError>): RequestResult<ReadinessResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadinessResponses, unknown, ThrowOnError>({ url: '/readyz', ...options });

/**
 * Read Current User
 *
 * Return the authenticated caller's identity.
 *
 * Proves the full loop: the Bearer token is verified against Clerk's JWKS
 * and the caller is resolved to (or JIT-created as) a local users row.
 */
export const currentUser = <ThrowOnError extends boolean = false>(options?: Options<CurrentUserData, ThrowOnError>): RequestResult<CurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CurrentUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me',
    ...options
});

/**
 * Upload Lab
 *
 * Upload a lab PDF, parse it into biomarker measurements, and store both.
 *
 * Synchronous end-to-end (~10-30 s). The original PDF is kept in GCS and the
 * upload row is retained even on parse failure, for debugging and retry.
 */
export const uploadLab = <ThrowOnError extends boolean = false>(options: Options<UploadLabData, ThrowOnError>): RequestResult<UploadLabResponses, UploadLabErrors, ThrowOnError> => (options.client ?? client).post<UploadLabResponses, UploadLabErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/lab-uploads',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * List Biomarkers
 *
 * Return each biomarker the caller has measurements for, with its time series.
 *
 * Values, units, and reference ranges are verbatim from the lab report;
 * canonical_unit is catalogue context. Series are sorted by measurement date
 * ascending, so the latest value is the last element.
 */
export const listBiomarkers = <ThrowOnError extends boolean = false>(options?: Options<ListBiomarkersData, ThrowOnError>): RequestResult<ListBiomarkersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListBiomarkersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/biomarkers',
    ...options
});
