// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * BiomarkerSeries
 */
export type BiomarkerSeries = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Canonical Unit
     */
    canonical_unit: string;
    /**
     * Measurements
     */
    measurements: Array<MeasurementPoint>;
};

/**
 * Body_upload_lab
 */
export type BodyUploadLab = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LabUploadResponse
 */
export type LabUploadResponse = {
    /**
     * Upload Id
     */
    upload_id: string;
    /**
     * Measured At
     */
    measured_at: string | null;
    /**
     * Measurements
     */
    measurements: Array<MeasurementOut>;
    /**
     * Skipped
     */
    skipped: Array<SkippedMarker>;
};

/**
 * MeResponse
 */
export type MeResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Clerk User Id
     */
    clerk_user_id: string;
};

/**
 * MeasurementOut
 */
export type MeasurementOut = {
    /**
     * Biomarker Slug
     */
    biomarker_slug: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Value
     */
    value: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Reference Low
     */
    reference_low: string | null;
    /**
     * Reference High
     */
    reference_high: string | null;
};

/**
 * MeasurementPoint
 */
export type MeasurementPoint = {
    /**
     * Measured At
     */
    measured_at: string | null;
    /**
     * Value
     */
    value: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Reference Low
     */
    reference_low: string | null;
    /**
     * Reference High
     */
    reference_high: string | null;
};

/**
 * SkippedMarker
 *
 * A marker that did not become a measurement, with why.
 */
export type SkippedMarker = {
    /**
     * Name
     */
    name: string;
    /**
     * Value
     */
    value: string;
    /**
     * Unit
     */
    unit: string | null;
    /**
     * Reason
     */
    reason: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type LivenessResponses = {
    /**
     * Response Liveness
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type LivenessResponse = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadinessResponses = {
    /**
     * Response Readiness
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadinessResponse = ReadinessResponses[keyof ReadinessResponses];

export type CurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type CurrentUserResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type CurrentUserResponse = CurrentUserResponses[keyof CurrentUserResponses];

export type UploadLabData = {
    body: BodyUploadLab;
    path?: never;
    query?: never;
    url: '/lab-uploads';
};

export type UploadLabErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadLabError = UploadLabErrors[keyof UploadLabErrors];

export type UploadLabResponses = {
    /**
     * Successful Response
     */
    200: LabUploadResponse;
};

export type UploadLabResponse = UploadLabResponses[keyof UploadLabResponses];

export type ListBiomarkersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/biomarkers';
};

export type ListBiomarkersResponses = {
    /**
     * Response List Biomarkers
     *
     * Successful Response
     */
    200: Array<BiomarkerSeries>;
};

export type ListBiomarkersResponse = ListBiomarkersResponses[keyof ListBiomarkersResponses];
