// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * BiomarkerMeasurementCreate
 */
export type BiomarkerMeasurementCreate = {
    /**
     * Biomarker Slug
     */
    biomarker_slug: string;
    /**
     * Value
     */
    value: number | string;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Measured At
     */
    measured_at: string;
    /**
     * Reference Low
     */
    reference_low?: number | string | null;
    /**
     * Reference High
     */
    reference_high?: number | string | null;
};

/**
 * BiomarkerMeasurementPoint
 */
export type BiomarkerMeasurementPoint = {
    /**
     * Id
     */
    id: string;
    /**
     * Measured At
     */
    measured_at: string;
    /**
     * Value
     */
    value: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Reference Low
     */
    reference_low: string | null;
    /**
     * Reference High
     */
    reference_high: string | null;
    /**
     * Lab Upload Id
     */
    lab_upload_id: string | null;
};

/**
 * BiomarkerMeasurementRead
 */
export type BiomarkerMeasurementRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Measured At
     */
    measured_at: string;
    /**
     * Value
     */
    value: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Reference Low
     */
    reference_low: string | null;
    /**
     * Reference High
     */
    reference_high: string | null;
    /**
     * Lab Upload Id
     */
    lab_upload_id: string | null;
    /**
     * Biomarker Slug
     */
    biomarker_slug: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * BiomarkerMeasurementUpdate
 */
export type BiomarkerMeasurementUpdate = {
    /**
     * Id
     */
    id: string;
    /**
     * Value
     */
    value?: number | string | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Measured At
     */
    measured_at?: string | null;
    /**
     * Reference Low
     */
    reference_low?: number | string | null;
    /**
     * Reference High
     */
    reference_high?: number | string | null;
};

/**
 * BiomarkerRead
 */
export type BiomarkerRead = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Canonical Unit
     */
    canonical_unit: string;
};

/**
 * BiomarkerSeries
 */
export type BiomarkerSeries = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Canonical Unit
     */
    canonical_unit: string;
    /**
     * Measurements
     */
    measurements: Array<BiomarkerMeasurementPoint>;
};

/**
 * Body_upload_lab
 */
export type BodyUploadLab = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LabDraft
 */
export type LabDraft = {
    /**
     * Measured At
     */
    measured_at: string | null;
    /**
     * Items
     */
    items: Array<LabDraftItemRead>;
    /**
     * Skipped
     */
    skipped: Array<LabDraftItemRead>;
};

/**
 * LabDraftItemRead
 */
export type LabDraftItemRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Biomarker Slug
     */
    biomarker_slug: string | null;
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Value
     */
    value: string | null;
    /**
     * Raw Value
     */
    raw_value: string | null;
    /**
     * Unit
     */
    unit: string | null;
    /**
     * Reference Low
     */
    reference_low: string | null;
    /**
     * Reference High
     */
    reference_high: string | null;
    /**
     * Source Name
     */
    source_name: string | null;
    /**
     * Skip Reason
     */
    skip_reason: string | null;
    /**
     * Included
     */
    included: boolean;
};

/**
 * LabDraftItemUpdate
 */
export type LabDraftItemUpdate = {
    /**
     * Id
     */
    id: string;
    /**
     * Value
     */
    value?: number | string | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Reference Low
     */
    reference_low?: number | string | null;
    /**
     * Reference High
     */
    reference_high?: number | string | null;
    /**
     * Included
     */
    included?: boolean | null;
    /**
     * Biomarker Slug
     */
    biomarker_slug?: string | null;
};

/**
 * LabDraftUpdate
 */
export type LabDraftUpdate = {
    /**
     * Measured At
     */
    measured_at?: string | null;
    /**
     * Items
     */
    items?: Array<LabDraftItemUpdate>;
};

/**
 * LabUploadDetail
 */
export type LabUploadDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Filename
     */
    filename: string;
    status: UploadStatus;
    /**
     * Measured At
     */
    measured_at: string | null;
    /**
     * Parsed At
     */
    parsed_at: string | null;
    /**
     * Committed At
     */
    committed_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Message
     */
    error_message: string | null;
    draft: LabDraft | null;
};

/**
 * LabUploadSummary
 */
export type LabUploadSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Filename
     */
    filename: string;
    status: UploadStatus;
    /**
     * Parsed At
     */
    parsed_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Measurement Count
     */
    measurement_count: number;
};

/**
 * MeResponse
 */
export type MeResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Clerk User Id
     */
    clerk_user_id: string;
};

/**
 * UploadStatus
 *
 * Lifecycle of a user-uploaded file, from receipt to committed record.
 *
 * pending → processing → awaiting_review → committed is the happy path;
 * failed is the terminal error branch from processing.
 */
export type UploadStatus = 'pending' | 'processing' | 'awaiting_review' | 'committed' | 'failed';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type LivenessResponses = {
    /**
     * Response Liveness
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type LivenessResponse = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadinessResponses = {
    /**
     * Response Readiness
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadinessResponse = ReadinessResponses[keyof ReadinessResponses];

export type CurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type CurrentUserResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type CurrentUserResponse = CurrentUserResponses[keyof CurrentUserResponses];

export type ListLabUploadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/lab-uploads';
};

export type ListLabUploadsResponses = {
    /**
     * Response List Lab Uploads
     *
     * Successful Response
     */
    200: Array<LabUploadSummary>;
};

export type ListLabUploadsResponse = ListLabUploadsResponses[keyof ListLabUploadsResponses];

export type UploadLabData = {
    body: BodyUploadLab;
    path?: never;
    query?: never;
    url: '/lab-uploads';
};

export type UploadLabErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadLabError = UploadLabErrors[keyof UploadLabErrors];

export type UploadLabResponses = {
    /**
     * Successful Response
     */
    202: LabUploadDetail;
};

export type UploadLabResponse = UploadLabResponses[keyof UploadLabResponses];

export type DeleteLabUploadData = {
    body?: never;
    path: {
        /**
         * Upload Id
         */
        upload_id: string;
    };
    query?: {
        /**
         * Delete Measurements
         */
        delete_measurements?: boolean;
    };
    url: '/lab-uploads/{upload_id}';
};

export type DeleteLabUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLabUploadError = DeleteLabUploadErrors[keyof DeleteLabUploadErrors];

export type DeleteLabUploadResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLabUploadResponse = DeleteLabUploadResponses[keyof DeleteLabUploadResponses];

export type GetLabUploadData = {
    body?: never;
    path: {
        /**
         * Upload Id
         */
        upload_id: string;
    };
    query?: never;
    url: '/lab-uploads/{upload_id}';
};

export type GetLabUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLabUploadError = GetLabUploadErrors[keyof GetLabUploadErrors];

export type GetLabUploadResponses = {
    /**
     * Successful Response
     */
    200: LabUploadDetail;
};

export type GetLabUploadResponse = GetLabUploadResponses[keyof GetLabUploadResponses];

export type UpdateLabDraftData = {
    body: LabDraftUpdate;
    path: {
        /**
         * Upload Id
         */
        upload_id: string;
    };
    query?: never;
    url: '/lab-uploads/{upload_id}/draft';
};

export type UpdateLabDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLabDraftError = UpdateLabDraftErrors[keyof UpdateLabDraftErrors];

export type UpdateLabDraftResponses = {
    /**
     * Successful Response
     */
    200: LabUploadDetail;
};

export type UpdateLabDraftResponse = UpdateLabDraftResponses[keyof UpdateLabDraftResponses];

export type ConfirmLabUploadData = {
    body?: never;
    path: {
        /**
         * Upload Id
         */
        upload_id: string;
    };
    query?: never;
    url: '/lab-uploads/{upload_id}/confirm';
};

export type ConfirmLabUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmLabUploadError = ConfirmLabUploadErrors[keyof ConfirmLabUploadErrors];

export type ConfirmLabUploadResponses = {
    /**
     * Successful Response
     */
    200: LabUploadDetail;
};

export type ConfirmLabUploadResponse = ConfirmLabUploadResponses[keyof ConfirmLabUploadResponses];

export type ListBiomarkersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/biomarkers';
};

export type ListBiomarkersResponses = {
    /**
     * Response List Biomarkers
     *
     * Successful Response
     */
    200: Array<BiomarkerRead>;
};

export type ListBiomarkersResponse = ListBiomarkersResponses[keyof ListBiomarkersResponses];

export type ListBiomarkerSeriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/biomarker-series';
};

export type ListBiomarkerSeriesResponses = {
    /**
     * Response List Biomarker Series
     *
     * Successful Response
     */
    200: Array<BiomarkerSeries>;
};

export type ListBiomarkerSeriesResponse = ListBiomarkerSeriesResponses[keyof ListBiomarkerSeriesResponses];

export type GetBiomarkerSeriesData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/biomarker-series/{slug}';
};

export type GetBiomarkerSeriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBiomarkerSeriesError = GetBiomarkerSeriesErrors[keyof GetBiomarkerSeriesErrors];

export type GetBiomarkerSeriesResponses = {
    /**
     * Successful Response
     */
    200: BiomarkerSeries;
};

export type GetBiomarkerSeriesResponse = GetBiomarkerSeriesResponses[keyof GetBiomarkerSeriesResponses];

export type DeleteBiomarkerMeasurementsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ids
         */
        ids: Array<string>;
    };
    url: '/biomarker-measurements';
};

export type DeleteBiomarkerMeasurementsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBiomarkerMeasurementsError = DeleteBiomarkerMeasurementsErrors[keyof DeleteBiomarkerMeasurementsErrors];

export type DeleteBiomarkerMeasurementsResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteBiomarkerMeasurementsResponse = DeleteBiomarkerMeasurementsResponses[keyof DeleteBiomarkerMeasurementsResponses];

export type UpdateBiomarkerMeasurementsData = {
    /**
     * Payload
     */
    body: Array<BiomarkerMeasurementUpdate>;
    path?: never;
    query?: never;
    url: '/biomarker-measurements';
};

export type UpdateBiomarkerMeasurementsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBiomarkerMeasurementsError = UpdateBiomarkerMeasurementsErrors[keyof UpdateBiomarkerMeasurementsErrors];

export type UpdateBiomarkerMeasurementsResponses = {
    /**
     * Response Update Biomarker Measurements
     *
     * Successful Response
     */
    200: Array<BiomarkerMeasurementRead>;
};

export type UpdateBiomarkerMeasurementsResponse = UpdateBiomarkerMeasurementsResponses[keyof UpdateBiomarkerMeasurementsResponses];

export type CreateBiomarkerMeasurementsData = {
    /**
     * Payload
     */
    body: Array<BiomarkerMeasurementCreate>;
    path?: never;
    query?: never;
    url: '/biomarker-measurements';
};

export type CreateBiomarkerMeasurementsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBiomarkerMeasurementsError = CreateBiomarkerMeasurementsErrors[keyof CreateBiomarkerMeasurementsErrors];

export type CreateBiomarkerMeasurementsResponses = {
    /**
     * Response Create Biomarker Measurements
     *
     * Successful Response
     */
    201: Array<BiomarkerMeasurementRead>;
};

export type CreateBiomarkerMeasurementsResponse = CreateBiomarkerMeasurementsResponses[keyof CreateBiomarkerMeasurementsResponses];
