/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as PhysiologyRouteImport } from './routes/physiology'
import { Route as OmicsRouteImport } from './routes/omics'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as BiomarkersRouteImport } from './routes/biomarkers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesUploadIdReviewRouteImport } from './routes/sources.$uploadId.review'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysiologyRoute = PhysiologyRouteImport.update({
  id: '/physiology',
  path: '/physiology',
  getParentRoute: () => rootRouteImport,
} as any)
const OmicsRoute = OmicsRouteImport.update({
  id: '/omics',
  path: '/omics',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BiomarkersRoute = BiomarkersRouteImport.update({
  id: '/biomarkers',
  path: '/biomarkers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesUploadIdReviewRoute = SourcesUploadIdReviewRouteImport.update({
  id: '/$uploadId/review',
  path: '/$uploadId/review',
  getParentRoute: () => SourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biomarkers': typeof BiomarkersRoute
  '/insights': typeof InsightsRoute
  '/interventions': typeof InterventionsRoute
  '/omics': typeof OmicsRoute
  '/physiology': typeof PhysiologyRoute
  '/sources': typeof SourcesRouteWithChildren
  '/sources/$uploadId/review': typeof SourcesUploadIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biomarkers': typeof BiomarkersRoute
  '/insights': typeof InsightsRoute
  '/interventions': typeof InterventionsRoute
  '/omics': typeof OmicsRoute
  '/physiology': typeof PhysiologyRoute
  '/sources': typeof SourcesRouteWithChildren
  '/sources/$uploadId/review': typeof SourcesUploadIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biomarkers': typeof BiomarkersRoute
  '/insights': typeof InsightsRoute
  '/interventions': typeof InterventionsRoute
  '/omics': typeof OmicsRoute
  '/physiology': typeof PhysiologyRoute
  '/sources': typeof SourcesRouteWithChildren
  '/sources/$uploadId/review': typeof SourcesUploadIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biomarkers'
    | '/insights'
    | '/interventions'
    | '/omics'
    | '/physiology'
    | '/sources'
    | '/sources/$uploadId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biomarkers'
    | '/insights'
    | '/interventions'
    | '/omics'
    | '/physiology'
    | '/sources'
    | '/sources/$uploadId/review'
  id:
    | '__root__'
    | '/'
    | '/biomarkers'
    | '/insights'
    | '/interventions'
    | '/omics'
    | '/physiology'
    | '/sources'
    | '/sources/$uploadId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiomarkersRoute: typeof BiomarkersRoute
  InsightsRoute: typeof InsightsRoute
  InterventionsRoute: typeof InterventionsRoute
  OmicsRoute: typeof OmicsRoute
  PhysiologyRoute: typeof PhysiologyRoute
  SourcesRoute: typeof SourcesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physiology': {
      id: '/physiology'
      path: '/physiology'
      fullPath: '/physiology'
      preLoaderRoute: typeof PhysiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omics': {
      id: '/omics'
      path: '/omics'
      fullPath: '/omics'
      preLoaderRoute: typeof OmicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biomarkers': {
      id: '/biomarkers'
      path: '/biomarkers'
      fullPath: '/biomarkers'
      preLoaderRoute: typeof BiomarkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$uploadId/review': {
      id: '/sources/$uploadId/review'
      path: '/$uploadId/review'
      fullPath: '/sources/$uploadId/review'
      preLoaderRoute: typeof SourcesUploadIdReviewRouteImport
      parentRoute: typeof SourcesRoute
    }
  }
}

interface SourcesRouteChildren {
  SourcesUploadIdReviewRoute: typeof SourcesUploadIdReviewRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesUploadIdReviewRoute: SourcesUploadIdReviewRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiomarkersRoute: BiomarkersRoute,
  InsightsRoute: InsightsRoute,
  InterventionsRoute: InterventionsRoute,
  OmicsRoute: OmicsRoute,
  PhysiologyRoute: PhysiologyRoute,
  SourcesRoute: SourcesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
