"""Seed data for `biomarker_intervals`, imported by the 0001 migration.

Extend this by appending dicts to ``INTERVALS`` — each is one canonical band,
keyed by biomarker ``slug`` (the migration resolves the slug to its id). Ages
are half-open ``[age_min_days, age_max_days)`` in canonical days; ``None`` means
unbounded (or, for ``age_min_days``, birth). ``sex`` is ``"male"``/``"female"``
or ``None`` (any). Either bound may be ``None`` for a one-sided interval.

Values are Karolinska Universitetslaboratoriet referensintervall in the
biomarker's canonical unit. Age labels from the source are normalized to
contiguous half-open ranges by tiling each band's upper to the next band's
lower. Years/months have no fixed day count, so the helpers approximate
(1 y = 365.25 d, 1 mo = 30.4375 d) — fine for partition boundaries.
"""

from decimal import Decimal

SOURCE = "Karolinska Universitetslaboratoriet"


# Age helpers: source labels → canonical days.
def years(n: float) -> int:
    return round(n * 365.25)


def months(n: float) -> int:
    return round(n * 30.4375)


def weeks(n: float) -> int:
    return n * 7


def days(n: int) -> int:
    return n


# Per-analyte Karolinska source pages.
GLUCOSE_URL = "https://www.karolinska.se/KUL/Alla-anvisningar/Anvisning/9095"
CHOLESTEROL_URL = "https://www.karolinska.se/pta/klinisk-kemi/kolesterol-p-/"
LDL_URL = "https://www.karolinska.se/pta/klinisk-kemi/ldl-kolesterol-fp-/"
HDL_URL = "https://www.karolinska.se/pta/klinisk-kemi/hdl-kolesterol-p-/"
TRIGLYCERIDES_URL = "https://www.karolinska.se/pta/klinisk-kemi/triglycerid-fp-/"
HBA1C_URL = "https://www.karolinska.se/KUL/Alla-anvisningar/Anvisning/9104"
TSH_URL = "https://www.karolinska.se/KUL/Alla-anvisningar/Anvisning/9311"
HEMOGLOBIN_URL = "https://www.karolinska.se/KUL/Alla-anvisningar/Anvisning/9112"
FERRITIN_URL = "https://www.karolinska.se/KUL/Alla-anvisningar/Anvisning/9074"
CREATININE_URL = "https://www.karolinska.se/KUL/Alla-anvisningar/Anvisning/9168"


INTERVALS: list[dict] = [
    # Glucose (mmol/L) — single fasting interval, all ages, unisex.
    {
        "slug": "glucose",
        "sex": None,
        "age_min_days": None,
        "age_max_days": None,
        "low": Decimal("4.2"),
        "high": Decimal("6.0"),
        "source": SOURCE,
        "source_url": GLUCOSE_URL,
    },
    # Total cholesterol (mmol/L) — sex split only at 15-17 y.
    {
        "slug": "total_cholesterol",
        "sex": None,
        "age_min_days": 0,
        "age_max_days": years(1),
        "low": Decimal("2.4"),
        "high": Decimal("5.3"),
        "source": SOURCE,
        "source_url": CHOLESTEROL_URL,
    },
    {
        "slug": "total_cholesterol",
        "sex": None,
        "age_min_days": years(1),
        "age_max_days": years(15),
        "low": Decimal("2.7"),
        "high": Decimal("5.9"),
        "source": SOURCE,
        "source_url": CHOLESTEROL_URL,
    },
    {
        "slug": "total_cholesterol",
        "sex": "female",
        "age_min_days": years(15),
        "age_max_days": years(18),
        "low": Decimal("2.4"),
        "high": Decimal("6.0"),
        "source": SOURCE,
        "source_url": CHOLESTEROL_URL,
    },
    {
        "slug": "total_cholesterol",
        "sex": "male",
        "age_min_days": years(15),
        "age_max_days": years(18),
        "low": Decimal("2.5"),
        "high": Decimal("5.4"),
        "source": SOURCE,
        "source_url": CHOLESTEROL_URL,
    },
    {
        "slug": "total_cholesterol",
        "sex": None,
        "age_min_days": years(18),
        "age_max_days": years(31),
        "low": Decimal("2.9"),
        "high": Decimal("6.1"),
        "source": SOURCE,
        "source_url": CHOLESTEROL_URL,
    },
    {
        "slug": "total_cholesterol",
        "sex": None,
        "age_min_days": years(31),
        "age_max_days": years(51),
        "low": Decimal("3.3"),
        "high": Decimal("6.9"),
        "source": SOURCE,
        "source_url": CHOLESTEROL_URL,
    },
    {
        "slug": "total_cholesterol",
        "sex": None,
        "age_min_days": years(51),
        "age_max_days": None,
        "low": Decimal("3.9"),
        "high": Decimal("7.8"),
        "source": SOURCE,
        "source_url": CHOLESTEROL_URL,
    },
    # LDL cholesterol (mmol/L) — unisex; source's 18-31/31-50 overlap split at 31.
    {
        "slug": "ldl_cholesterol",
        "sex": None,
        "age_min_days": 0,
        "age_max_days": years(1),
        "low": Decimal("0.8"),
        "high": Decimal("3.5"),
        "source": SOURCE,
        "source_url": LDL_URL,
    },
    {
        "slug": "ldl_cholesterol",
        "sex": None,
        "age_min_days": years(1),
        "age_max_days": years(18),
        "low": Decimal("1.3"),
        "high": Decimal("4.0"),
        "source": SOURCE,
        "source_url": LDL_URL,
    },
    {
        "slug": "ldl_cholesterol",
        "sex": None,
        "age_min_days": years(18),
        "age_max_days": years(31),
        "low": Decimal("1.2"),
        "high": Decimal("4.3"),
        "source": SOURCE,
        "source_url": LDL_URL,
    },
    {
        "slug": "ldl_cholesterol",
        "sex": None,
        "age_min_days": years(31),
        "age_max_days": years(51),
        "low": Decimal("1.4"),
        "high": Decimal("4.7"),
        "source": SOURCE,
        "source_url": LDL_URL,
    },
    {
        "slug": "ldl_cholesterol",
        "sex": None,
        "age_min_days": years(51),
        "age_max_days": None,
        "low": Decimal("2.0"),
        "high": Decimal("5.3"),
        "source": SOURCE,
        "source_url": LDL_URL,
    },
    # HDL cholesterol (mmol/L) — sex split at 15-17 y and adult.
    {
        "slug": "hdl_cholesterol",
        "sex": None,
        "age_min_days": 0,
        "age_max_days": years(15),
        "low": Decimal("0.7"),
        "high": Decimal("1.9"),
        "source": SOURCE,
        "source_url": HDL_URL,
    },
    {
        "slug": "hdl_cholesterol",
        "sex": "female",
        "age_min_days": years(15),
        "age_max_days": years(18),
        "low": Decimal("0.6"),
        "high": Decimal("2.2"),
        "source": SOURCE,
        "source_url": HDL_URL,
    },
    {
        "slug": "hdl_cholesterol",
        "sex": "male",
        "age_min_days": years(15),
        "age_max_days": years(18),
        "low": Decimal("0.7"),
        "high": Decimal("1.8"),
        "source": SOURCE,
        "source_url": HDL_URL,
    },
    {
        "slug": "hdl_cholesterol",
        "sex": "female",
        "age_min_days": years(18),
        "age_max_days": None,
        "low": Decimal("1.0"),
        "high": Decimal("2.7"),
        "source": SOURCE,
        "source_url": HDL_URL,
    },
    {
        "slug": "hdl_cholesterol",
        "sex": "male",
        "age_min_days": years(18),
        "age_max_days": None,
        "low": Decimal("0.8"),
        "high": Decimal("2.1"),
        "source": SOURCE,
        "source_url": HDL_URL,
    },
    # Triglycerides (mmol/L) — unisex, fasting.
    {
        "slug": "triglycerides",
        "sex": None,
        "age_min_days": 0,
        "age_max_days": years(1),
        "low": Decimal("0.59"),
        "high": Decimal("2.6"),
        "source": SOURCE,
        "source_url": TRIGLYCERIDES_URL,
    },
    {
        "slug": "triglycerides",
        "sex": None,
        "age_min_days": years(1),
        "age_max_days": years(18),
        "low": Decimal("0.43"),
        "high": Decimal("2.8"),
        "source": SOURCE,
        "source_url": TRIGLYCERIDES_URL,
    },
    {
        "slug": "triglycerides",
        "sex": None,
        "age_min_days": years(18),
        "age_max_days": None,
        "low": Decimal("0.45"),
        "high": Decimal("2.6"),
        "source": SOURCE,
        "source_url": TRIGLYCERIDES_URL,
    },
    # HbA1c (mmol/mol) — unisex; the <50 y band has no lower age bound.
    {
        "slug": "hba1c",
        "sex": None,
        "age_min_days": None,
        "age_max_days": years(50),
        "low": Decimal("27"),
        "high": Decimal("42"),
        "source": SOURCE,
        "source_url": HBA1C_URL,
    },
    {
        "slug": "hba1c",
        "sex": None,
        "age_min_days": years(50),
        "age_max_days": None,
        "low": Decimal("31"),
        "high": Decimal("46"),
        "source": SOURCE,
        "source_url": HBA1C_URL,
    },
    # TSH (mIU/L; page unit mE/L) — unisex, age-dependent.
    {
        "slug": "tsh",
        "sex": None,
        "age_min_days": 0,
        "age_max_days": weeks(1),
        "low": Decimal("0.7"),
        "high": Decimal("15"),
        "source": SOURCE,
        "source_url": TSH_URL,
    },
    {
        "slug": "tsh",
        "sex": None,
        "age_min_days": weeks(1),
        "age_max_days": months(4),
        "low": Decimal("0.7"),
        "high": Decimal("11"),
        "source": SOURCE,
        "source_url": TSH_URL,
    },
    {
        "slug": "tsh",
        "sex": None,
        "age_min_days": months(4),
        "age_max_days": years(1),
        "low": Decimal("0.7"),
        "high": Decimal("8.4"),
        "source": SOURCE,
        "source_url": TSH_URL,
    },
    {
        "slug": "tsh",
        "sex": None,
        "age_min_days": years(1),
        "age_max_days": years(7),
        "low": Decimal("0.7"),
        "high": Decimal("6.0"),
        "source": SOURCE,
        "source_url": TSH_URL,
    },
    {
        "slug": "tsh",
        "sex": None,
        "age_min_days": years(7),
        "age_max_days": years(12),
        "low": Decimal("0.6"),
        "high": Decimal("4.8"),
        "source": SOURCE,
        "source_url": TSH_URL,
    },
    {
        "slug": "tsh",
        "sex": None,
        "age_min_days": years(12),
        "age_max_days": years(19),
        "low": Decimal("0.5"),
        "high": Decimal("4.3"),
        "source": SOURCE,
        "source_url": TSH_URL,
    },
    {
        "slug": "tsh",
        "sex": None,
        "age_min_days": years(19),
        "age_max_days": None,
        "low": Decimal("0.3"),
        "high": Decimal("4.2"),
        "source": SOURCE,
        "source_url": TSH_URL,
    },
    # Hemoglobin (g/L) — many neonatal/pediatric bands, adult sex split.
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": 0,
        "age_max_days": days(2),
        "low": Decimal("150"),
        "high": Decimal("240"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": days(2),
        "age_max_days": days(7),
        "low": Decimal("140"),
        "high": Decimal("220"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": days(7),
        "age_max_days": days(22),
        "low": Decimal("130"),
        "high": Decimal("200"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": days(22),
        "age_max_days": months(1),
        "low": Decimal("100"),
        "high": Decimal("180"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": months(1),
        "age_max_days": months(4),
        "low": Decimal("100"),
        "high": Decimal("160"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": months(4),
        "age_max_days": years(1),
        "low": Decimal("100"),
        "high": Decimal("140"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": years(1),
        "age_max_days": years(7),
        "low": Decimal("100"),
        "high": Decimal("150"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": years(7),
        "age_max_days": years(11),
        "low": Decimal("105"),
        "high": Decimal("150"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": None,
        "age_min_days": years(11),
        "age_max_days": years(18),
        "low": Decimal("110"),
        "high": Decimal("160"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": "female",
        "age_min_days": years(18),
        "age_max_days": None,
        "low": Decimal("117"),
        "high": Decimal("153"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    {
        "slug": "hemoglobin",
        "sex": "male",
        "age_min_days": years(18),
        "age_max_days": None,
        "low": Decimal("134"),
        "high": Decimal("170"),
        "source": SOURCE,
        "source_url": HEMOGLOBIN_URL,
    },
    # Ferritin (µg/L) — Karolinska publishes adults only; under-18 unbanded.
    {
        "slug": "ferritin",
        "sex": "female",
        "age_min_days": years(18),
        "age_max_days": None,
        "low": Decimal("13"),
        "high": Decimal("150"),
        "source": SOURCE,
        "source_url": FERRITIN_URL,
    },
    {
        "slug": "ferritin",
        "sex": "male",
        "age_min_days": years(18),
        "age_max_days": None,
        "low": Decimal("30"),
        "high": Decimal("400"),
        "source": SOURCE,
        "source_url": FERRITIN_URL,
    },
    # Creatinine (µmol/L) — upper-bound only; per-year pediatric, sex split from 13 y.
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": 0,
        "age_max_days": days(15),
        "low": None,
        "high": Decimal("77"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": days(15),
        "age_max_days": months(2),
        "low": None,
        "high": Decimal("60"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": months(2),
        "age_max_days": years(3),
        "low": None,
        "high": Decimal("41"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(3),
        "age_max_days": years(4),
        "low": None,
        "high": Decimal("44"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(4),
        "age_max_days": years(5),
        "low": None,
        "high": Decimal("47"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(5),
        "age_max_days": years(6),
        "low": None,
        "high": Decimal("50"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(6),
        "age_max_days": years(7),
        "low": None,
        "high": Decimal("53"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(7),
        "age_max_days": years(8),
        "low": None,
        "high": Decimal("56"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(8),
        "age_max_days": years(9),
        "low": None,
        "high": Decimal("59"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(9),
        "age_max_days": years(10),
        "low": None,
        "high": Decimal("62"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(10),
        "age_max_days": years(11),
        "low": None,
        "high": Decimal("65"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(11),
        "age_max_days": years(12),
        "low": None,
        "high": Decimal("68"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": None,
        "age_min_days": years(12),
        "age_max_days": years(13),
        "low": None,
        "high": Decimal("71"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "female",
        "age_min_days": years(13),
        "age_max_days": years(14),
        "low": None,
        "high": Decimal("74"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "male",
        "age_min_days": years(13),
        "age_max_days": years(14),
        "low": None,
        "high": Decimal("84"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "female",
        "age_min_days": years(14),
        "age_max_days": years(15),
        "low": None,
        "high": Decimal("77"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "male",
        "age_min_days": years(14),
        "age_max_days": years(15),
        "low": None,
        "high": Decimal("87"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "female",
        "age_min_days": years(15),
        "age_max_days": years(16),
        "low": None,
        "high": Decimal("80"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "male",
        "age_min_days": years(15),
        "age_max_days": years(16),
        "low": None,
        "high": Decimal("90"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "female",
        "age_min_days": years(16),
        "age_max_days": years(17),
        "low": None,
        "high": Decimal("83"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "male",
        "age_min_days": years(16),
        "age_max_days": years(17),
        "low": None,
        "high": Decimal("93"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "female",
        "age_min_days": years(17),
        "age_max_days": years(18),
        "low": None,
        "high": Decimal("86"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "male",
        "age_min_days": years(17),
        "age_max_days": years(18),
        "low": None,
        "high": Decimal("96"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "female",
        "age_min_days": years(18),
        "age_max_days": None,
        "low": None,
        "high": Decimal("90"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
    {
        "slug": "creatinine",
        "sex": "male",
        "age_min_days": years(18),
        "age_max_days": None,
        "low": None,
        "high": Decimal("100"),
        "source": SOURCE,
        "source_url": CREATININE_URL,
    },
]
